name: pnpm-install-with-retries
description: "wraps pnpm install with retries/timeout to handle network failures"
inputs:
  ignore-scripts:
    type: boolean
    default: false
    description: "Skip pre/post install scripts"
runs:
  using: composite
  steps:
    - name: pnpm install
      uses: ClayChipps/sf-chipps-github-workflows/.github/actions/retry@main
      with:
        command: pnpm install ${{ inputs.ignore-scripts && '--ignore-scripts' || '' }}
