name: ctcClose
description: "closes a given change case in GUS. Will throw and provide a message if env is misconfigured"
inputs:
  changeCaseId:
    description: "Id for the change case created"
    required: true
  status:
    required: false
    description: CTC status, like "Implemented - per plan", "Not Implemented"
    default: Implemented - per plan

runs:
  using: "composite"
  steps:
    - id: ctc
      run: |
        if [ -z "${SF_CHANGE_CASE_SFDX_AUTH_URL}" ] || [ -z "${SF_CHANGE_CASE_TEMPLATE_ID}" ] || [ -z "${SF_CHANGE_CASE_CONFIGURATION_ITEM}" ] ; then
          echo "Environment not configured for CTC.  Your environment needs SF_CHANGE_CASE_SFDX_AUTH_URL, SF_CHANGE_CASE_TEMPLATE_ID, and SF_CHANGE_CASE_CONFIGURATION_ITEM"
          exit 1
        else
          sfchangecase close --location ${{ github.repositoryUrl }} --changecaseid ${{ inputs.changeCaseId}} --status ${{ inputs.status }}
        fi
      shell: bash
