on:
  workflow_call:

jobs:
  updateDevScripts:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
      - uses: salesforcecli/github-workflows/.github/actions/gitConfig@main

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
      - run: npm install -g yarn-deduplicate
      - run: yarn upgrade @salesforce/dev-scripts@latest
      # this may fail because that's how dev-scripts does things
      - run: yarn install --network-timeout 600000
        continue-on-error: true

      - run: yarn install --network-timeout 600000
      - run: npx yarn-deduplicate
      - run: yarn install --network-timeout 600000

      - run: |
          git checkout -b devScripts$(date +%F)
          yarn lint --fix
          git add .
          git commit -m 'chore: updates from devScripts'
          git push origin
          gh pr create --title 'devScripts update'
        continue-on-error: true
