name: tag and github release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Conventional Changelog Action
        id: changelog
        uses: TriPSs/conventional-changelog-action@d360fad3a42feca6462f72c97c165d60a02d4bf2
        with:
          git-user-name: ${{ github.actor }}
          git-user-email: alm-cli@salesforce.com
          github-token: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
          output-file: "false"
      - name: Create Github Release
        run: gh release create ${{ steps.changelog.outputs.tag }} -F CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ secrets.SF_CLI_BOT_GITHUB_TOKEN }}
