on:
  workflow_call:
    inputs:
      cli:
        type: string
        required: true
        description: only needed if upload. sfdx or sf
      version:
        type: string
        required: true
        description: version for upload. do not include the 'v'
      channel:
        type: string
        required: true
        description: channel that the uploaded tarballs get promoted to

jobs:
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn pack:macos
      - run: yarn upload:macos
      - run: yarn channel:promote --cli ${{ inputs.cli }} --version ${{ inputs.version }} --target ${{ inputs.channel }} --platform macos
        name: Promote macos to ${{ inputs.channel }} channel
