on:
  workflow_call:

jobs:
  test-pack-tarballs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: yarn
      - run: yarn install
      - run: yarn pack:tarballs
      - run: yarn pack:verify
      - run: yarn test:smoke-unix
