on:
  workflow_call:

jobs:
  linux-unit-tests:
    uses: ClayChipps/sf-chipps-github-workflows/.github/workflows/unitTestsLinux.yml@main
  windows-unit-tests:
    uses: ClayChipps/sf-chipps-github-workflows/.github/workflows/unitTestsWindows.yml@main
