on:
  workflow_call:

jobs:
  determine-node-versions:
    runs-on: ubuntu-latest
    outputs:
      nodeVersions: ${{ steps.node-versions.outputs.nodeVersions }}
    steps:
      - name: Determine node versions
        id: node-versions
        run: |
          NODE_VERSION="${{ vars.NODE_VERSION_OVERRIDE || 'lts/*' }}"
          NODE_VERSION_MINUS_ONE="lts/-1"

          if [ -n "${{ vars.NODE_VERSION_OVERRIDE }}" ]; then
            NODE_VERSION_MAJOR=$(echo "${{ vars.NODE_VERSION_OVERRIDE }}" | cut -d '.' -f 1)
            NODE_VERSION_MINUS_ONE="$((NODE_VERSION_MAJOR - 1))"
          fi

          {
            echo 'nodeVersions<<EOF'
            [
              "$NODE_VERSION",
              "$NODE_VERSION_MINUS_ONE"
            ]
            echo EOF
          } >> "$GITHUB_OUTPUT"

  linux-unit-tests:
    needs: determine-node-versions
    strategy:
      matrix:
        node_version: ${{ fromJSON(needs.determine-node-versions.outputs.nodeVersions) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: yarn
      - uses: google/wireit@setup-github-actions-caching/v1
        continue-on-error: true
      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}

      - uses: salesforcecli/github-workflows/.github/actions/yarnInstallWithRetries@main
        if: ${{ steps.cache-nodemodules.outputs.cache-hit != 'true' }}
      - run: yarn build
      - name: yarn test
        uses: salesforcecli/github-workflows/.github/actions/retry@ew/retry-wrapper
        with:
          command: yarn test
        env:
          SF_DISABLE_TELEMETRY: true
